name: Run Server

description: Run the mockserver for F1Betting

inputs:
  input-folder:
    required: true
    description: The input folder that contains the OpenAPI specs and optional custom configuration
  disable-versioning:
    required: false
    description: Disable automatic versioning based on OpenAPI specifications

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Convert OpenAPI spec to KrakenD
      shell: bash
      run: |
        mkdir -p output
        export PYTHONPATH=${{ github.action_path }}
        
        echo "python -m app.main ${{inputs.input-folder}} output \
          $(if [ -n "${{inputs.disable-versioning}}" ]; then echo " --disable-automatic-versioning"; fi)"
        
        python -m app.main ${{inputs.input-folder}} output \
          $(if [ -n "${{inputs.disable-versioning}}" ]; then echo " --disable-automatic-versioning"; fi)

    - name: Upload output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: krakend-config
        path: ./output/
        retention-days: 14