name: Convert Specs to KrakenD config

on: workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Convert specs to KrakenD config
        uses: f1betting/OpenAPItoKrakenD@v2
        with:
          input-folder: specs

  build:
    needs: [ convert ]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - name: Download KrakenD configuration
        uses: actions/download-artifact@v2
        with:
          name: krakend-config

      - name: Authenticate Google SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GOOGLE_ACCOUNT_CREDENTIALS}}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Build docker-image and submit to GCR'
        run: 'gcloud builds submit --tag gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/${{secrets.GOOGLE_SERVICE_NAME}} . --timeout 3600'

  deploy:
    needs: [ convert, build ]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - name: Authenticate Google SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GOOGLE_ACCOUNT_CREDENTIALS}}

      - name: Deploy to Google Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: gcr.io/${{secrets.GOOGLE_PROJECT_ID}}/${{secrets.GOOGLE_SERVICE_NAME}}
          service: ${{secrets.GOOGLE_SERVICE_NAME}}
          region: europe-west1